### ISSUE TITLE
Webix Jet - $onurlchange's config and url arguments are empty arrays

### ISSUE THREAD

**Issue by dxps** [webix-hub/jet-demos#2]
Hello,

While learning Webix Jet and playing with the samples, I have noticed that both `config` and `url` arguments of `$onurlchange(config, url, $scope)` method are empty arrays.

This can be seen on [05_view_handler](https://github.com/webix-hub/jet-demos/tree/05_view_handlers) sample:

``` javascript
        $onurlchange:function(config, url, $scope) {
            // $$("top:menu").select(url[0].page);
            console.log('>>> $onurlchange > called. see below the following objects: config, url');
            console.log(config);
            console.log(url);
        }
```

As mentioned in [View Handlers](https://webix.gitbooks.io/webix-jet/content/chapter2.html) section of Webix Jet book, the three arguments of `$onurlchange(...)` means:
- config - parameters of the url
- url - contains the names of segments and all parameters of the url
- $scope - the current scope

Therefore, is there something missing?

Thanks.

**Comment by Zwillinge** [comment]
Hello, 

You are right, there's an inconsistency in our book. There parameters are passed only under specific conditions: 
- **config** contains url parameters that are passed as `/jet-demos/#!/top/data:id=3/form` in the url string. In the `data.js` file you can catch this ID. Please,  check the related [18_url_params](https://github.com/webix-hub/jet-demos/tree/18_url_params) branch.
- **url** contains information about _additional_ parts of the url that does not correspond to related subviews. If the link is `/jet-demos/#!/top/data:id=3/form/info/test` and you have `top.js`, `data.js` and `form.js` files (as in the sample), so `url` will be as follows: 

```
[  {page:"info", params[]}, { page:"test", params:[] } ]
```

As you can see, these "page" url parts can also have their own parameters, like `/info:id=5/`.

**Comment by dxps** [comment]
Hi Helga,

First of all, thank you for the feedback! 😄 
I got it and I hope the book will be updated to reflect this case.

Thanks
